export const furniture = [
    {
        id: 1,
        name: "Mid Century Modern Accent Chair",
        image: './arm1.jpg',
        minPrice: '25000.00',
        maxPrice: '30000.00',
        quantity: 10,
        type: 'chair',
        isLiked: true,
        rating: 5,
        addedToCart: true,
    },
    {
        id: 2,
        name: "Linen Armchair",
        image: './arm2.jpg',
        minPrice: '35000.00',
        maxPrice: '37000.00',
        quantity: 10,
        type: 'chair',
        isLiked: true,
        rating: 4,
        addedToCart: false,

    },
    {
        id: 3,
        name: "Wooden Chair",
        image: './chair1.jpg',
        minPrice: '12000.00',
        maxPrice: '14000.00',
        quantity: 10,
        type:'chair',
        isLiked: true,
        rating: 3.5,
        addedToCart: true,
    },
    {
        id: 4,
        name: "High Back Gaming Chair",
        image: './gamingChair.jpg',
        minPrice: '35000.00',
        maxPrice: '38000.00',
        quantity: 20,
        type:'chair',
        isLiked: false,
        rating: 5,
        addedToCart: false,
    },
    {
        id: 5,
        name: "High Back Gaming Chair",
        image: './arm2.jpg',
        minPrice: '35000.00',
        maxPrice: '38000.00',
        quantity: 20,
        type:'chair',
        isLiked: false,
        rating: 5,
        addedToCart: false,
    }
]